### ISSUE TITLE
just screen off with aod on and ability to manually choose apps

### ISSUE THREAD

**Issue by bayfisher** [Chainfire/HoleyLight#10]
I will gladly pay 10.00 if this app ever is completed without a second thought.

**Comment by Chainfire** [comment]
Why do you manually need to choose apps? You can already configure any app that triggers LED (after the app has triggered it once, it will be listed in Holey Light's Color page). Add apps that do not trigger LED would bring you nothing.

**Comment by bayfisher** [comment]
I assumed like glimpse you had to select. And still if you get it to work
screen off I will still pay. Period.

**Comment by bayfisher** [comment]
Hey,

I just signed the petition "Give $2000/month to every American
#moneyforthepeople #covid19" and wanted to see if you could help by adding
your name.

Our goal is to reach 1,500,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/RmrPK6PX94

Thanks!
LEONARD
