### ISSUE TITLE
Please define "respect notification color state" parameter

### ISSUE THREAD

**Issue by JoelAzaria** [Chainfire/HoleyLight#108]
What does this parameter do/affect?

The two possible values are `respect` and `ignore`.   What are the consequences of each?

Thank you.

Edit to add:   This setting is in Colors when you press-hold an application/event name.  3rd option down.  thx.

**Comment by d7415** [comment]
Apps can set the colour of their notifications. IIRC this setting lets you "respect" (use) that colour or "ignore" it and use one you specify.
