### ISSUE TITLE
Support custom colors for different notifications requested by the same app

### ISSUE THREAD

**Issue by muttley79** [Chainfire/HoleyLight#19]
(Added better name for the issue)

**Comment by Chainfire** [comment]
I don't understand

**Comment by muttley79** [comment]
Currently, apps like Whatsapp or Textra allow custom led color for specific contact
Whatsapp allows also different led color for groups
If it's possible to get the led color value sent to the "non-existing" led on the phone, and adjust the ring color to it

**Comment by Chainfire** [comment]
#30
