### ISSUE TITLE
Battery indicator

### ISSUE THREAD

**Issue by Chainfire** [Chainfire/HoleyLight#23]
Much requested

**Comment by aygz** [comment]
is it possible ?
When the phone is charging while the red LED is on and led is turn to green on full charged. 
(Like S8/S9)

**Comment by ripclaw2002** [comment]
I would like this too as well please

**Comment by acarpiop** [comment]
Me too, is very useful. Thanks

**Comment by Chainfire** [comment]
With Unholey Light setting, maybe put battery percentage in the middle?

**Comment by ripclaw2002** [comment]
if the cutout light can show if battery is full - solid green as opposed to charging (maybe swirling orange or blinking orange), i think that would work

**Comment by androidbotz** [comment]
Those using Holey Light and wanting a light notification for battery status can do the following :

Go to Holey Light > Colors >

(for low battery notification look for..)
System UI LBT

(for battery full notification look for..)
System UI FBT

and set the desired colour you want.

**Comment by muttley79** [comment]
I believe most people would like also a "charging" indication of some sort, like the actual led would do
maybe "reverse swirl" animation can mean this is a charging process not a regular notification.

**Comment by androidbotz** [comment]
> I believe most people would like also a "charging" indication of some sort, like the actual led would do
> maybe "reverse swirl" animation can mean this is a charging process not a regular notification.

Yup, a different pattern would be ideal but if you need to know the "charging in process" indication/notification then you can use **System UI GEN** channel and select a different colour for each process/channel in the mean time.
