### ISSUE TITLE
Reports of dismissal not working right

### ISSUE THREAD

**Issue by Chainfire** [Chainfire/HoleyLight#26]
See https://forum.xda-developers.com/showpost.php?p=79303854&postcount=331 , point 2

**Comment by Covafett** [comment]
Using S10+. If the messaging app (Samsung's) is open and the screen is off and a new message comes in, the ring notification activates and stays even after I go into the conversation and respond. If I clear all open apps, the light persists until I do a restart or close the app and another message comes in and I reopen the messaging app.

**Comment by Chainfire** [comment]
Also see: https://forum.xda-developers.com/showpost.php?p=79307068&postcount=373

**Comment by Chainfire** [comment]
Also see: https://forum.xda-developers.com/member.php?u=9839677
