### ISSUE TITLE
Add a timer

### ISSUE THREAD

**Issue by Bytypez** [Chainfire/HoleyLight#28]
Possibly add a timer so the LED only flashes every 8-12 seconds?

**Comment by Chainfire** [comment]
Maybe. To what purpose exactly? It will not reduce battery use, unless the interval goes into the minute (rather than second) range

**Comment by Bytypez** [comment]
If it does not improve battery life, you can just leave it as it is then :)

**Comment by Starburst888** [comment]
I think another reason is so it's not a constant notification. When there are interval lights it tends to catch the eye more than a constant light. As the LED worked on the previous Samsung phones, having an interval of the notification grabbed my attention and reminded me of my notification. where as the constant swirl or just steady light it's easier to blend into the screen.

Just another perspective

**Comment by Chainfire** [comment]
Sure, but doesn't enabling the battery saving animation take care of that? It blinks rather than swirls.

**Comment by Starburst888** [comment]
Correct, the battery saving animation allows a blinking animation but when I try adjusting the speed of the blink, the desire would be for the flashes to be a greater distance apart than on and off really fast or slowing down or speeding up the whole animation.

As you stated on your main page, this app is for you and you've generously provided it to us as well. What you've created is absolutely amazing in the first place and I want to make that known. 

I've had the s4 and s8 my whole "smartphone life" and just got used to that feature.  Again, really appreciate what you have done.

**Comment by Bytypez** [comment]
I agree with Starburst. A small timer setting to set the interval would be deeply appreciated!

**Comment by Chainfire** [comment]
Additionally: allow notifications to timeout

**Comment by spuyelli** [comment]
Hi Chainfire. First, I've downloaded your app just yesterday and I love it. Thank you for sharing it!

About the issue, I believe Bytypez and Starburst888 are referring a delay method or something similar so there is a delay time in between a full animation cycle (swirl, pause(Xseconds), swirl again).
I believe it would be useful and look nice if you could add that.

Again, thank you for the amazing app.
