### ISSUE TITLE
Permission stop optimizing battery usage 

### ISSUE THREAD

**Issue by aygz** [Chainfire/HoleyLight#41]
I tried this for battery save. I didn't give allow 4/4 permission (stop optimizing battery usage) when installing the app.  I've been using this way for a few days, Holey led notification is working perfectly (without any problems) and battery drain around 0%
(19 hours 0,4%)
It's worth a try.

**Comment by Chainfire** [comment]
Android will randomly kill Holey Light. This is not advisable.
