### ISSUE TITLE
Colors: Hex/RGB values in color picker

### ISSUE THREAD

**Issue by nweddle** [Chainfire/HoleyLight#44]
As an app user, I would like to be able to specify exact color values for each notification channel. 

This will be useful for folks who are looking to match app colors exactly, or for device theming purposes.

Love the app, it's terrific!

**Comment by androidbotz** [comment]
First off, @Chainfire props to you for all your good work. Moving onto business, couldn't agree more with @nweddle. Personally, I've got 4 Gmail accounts and other similar notification channels as well but unfortunately, all are a shade different then the other. Having it in Hex/RGB will standardize things and make the palette so much easier to operate with my stubby fingers. Peace!
