### ISSUE TITLE
Double-Tap gets unresponsive on "Hide AOD" (ISSUE FIXED)

### ISSUE THREAD

**Issue by androidbotz** [Chainfire/HoleyLight#63]
Not sure if its just related to my phone but have noticed that double-tap function gets less responsive or even unresponsive at times if phone is not used for a good 15-30 minutes while "Hide AOD" is enabled in either partial or full.

When I disable "Hide AOD" in Holey Light is seems to work fine.

Using Ver 0.66

**EDIT: Issue fixed by much trial and error.**

**Comment by jeje2016** [comment]
hello I see problem solved how did you do it?

**Comment by himisk71** [comment]
I am interested too. No matter what i change in settings, sometimes i can not wake up the display with the double tap... All other is working very well.

**Comment by Chainfire** [comment]
The location where you tap matters. If you double tap where the AOD image is (which is hidden) then it sometimes doesn't work.

**Comment by jeje2016** [comment]
I disable "Hide AOD" in Holey Light is seems to work fine. aod original fonctionne
