### ISSUE TITLE
Allow animation fine tuning

### ISSUE THREAD

**Issue by Chainfire** [Chainfire/HoleyLight#7]
Position and speed

**Comment by ninjaengineers** [comment]
I just want to say that you're awesome! Thank you! :D

**Comment by tespio** [comment]
> 
> 
> I just want to say that you're awesome! Thank you! :D

I second that! Awesome job!

**Comment by gdidok** [comment]
Big thumbs up for making the app! 
I think Animation Interval could be a useful parameter.
