### ISSUE TITLE
notification ring not showing up when screen is off

### ISSUE THREAD

**Issue by amyvon** [Chainfire/HoleyLight#76]
I am not seeing a notification when the screen is off, even though I have it set to show in the settings. It shows on the lock screen and when the screen is on only. It was working earlier today, and now it isn't. I was playing the AOD settings, but now I have it set to fully hide AOD in settings. Please advise Thank you!

**Comment by opicak** [comment]
I have the same problem even now. But I'm not sure if you mean that the display is completely off or when AOD enabled but only in "tap to show" mode (= most of the time it's fully black)?
