### ISSUE TITLE
Camera cutout light even when no notification

### ISSUE THREAD

**Issue by tespio** [Chainfire/HoleyLight#8]
When the screen is unlocked the camera cutout lights out even when no notifications. See https://photos.app.goo.gl/z5aRvKqokhinRYAp7

**Comment by Chainfire** [comment]
Using the new color adjustment screen in v0.20, can you try figuring out which app is causing the leftover notification?

**Comment by tespio** [comment]
Now it seems to be okay. I tested with whatsapp, light was green, on normal sms light was blue. Once read light went off. Does it automatically takes the color from the app icons or are they predefined in the app itself?

**Comment by Chainfire** [comment]
It takes the color for the LED color the app in question requests in the notification. Except when the requested color is white, then it tries to base it on the app's accent color (also passed into the notification).
