### ISSUE TITLE
Not work on One UI 3.0  (S10)

### ISSUE THREAD

**Issue by puppyjn** [Chainfire/HoleyLight#84]
0.70  Not work on One UI 3.0 with my S10  just pushed by samsung.  While it works on 2.5 for years, thanks for Chainfire!

I built the app from source code v0.70,  using Unholey Light mode,  it not works.

I added following code before line 260 in NotificationAnimation.java:
>  **tspRect.bottom = resolution.y;** 

then the cycle appered, but there are still something wrong:

1. Occasionally not works. no cycle and AOD still displayed;
2. When enable icon in cycle, the icon stick on surface even in app screen while the cycle disappeared.
3. After notification is cleared,  I think there must be a transparent overlay on screen, because finger touchs in the area not works.
4. Part of the cycle is often covered by black, especially when the phone is not charged.

**Comment by Chainfire** [comment]
Working on a new version, debugging @ Telegram. Feel free to join - https://t.me/joinchat/I8HshhIHzwrJalUJ
